<?php
define('ADMIN_USER', 'admin');
// Use a secure bcrypt hash generated by password_hash('YourPassword', PASSWORD_BCRYPT)
define('ADMIN_HASH', '$2y$12$REPLACE_WITH_YOUR_SECURE_BCRYPT_PASSWORD_HASH_HERE');
?>
