<?php
define('ADMIN_USER', 'admin');
// Use a secure bcrypt hash generated by password_hash('YourPassword', PASSWORD_BCRYPT)
define('ADMIN_HASH', '$2y$12$P1j39/.VeagHjJ.Lt08yNuSDQPH/3TT.Iq4H2bHElsDtFIcQN9H/O'); // Password: PrimePath2024!
?>
